import { StyleSheet } from "react-native";

export default StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: "#fff7fb",
  },
  mainMenuWrapper: {
    paddingHorizontal: 16,
    paddingTop: 8,
    backgroundColor: "#fff7fb",
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingTop: 8,
    paddingBottom: 100,
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
    alignItems: "center",
  },
  avatarLeft: {
    width: 40,
    height: 40,
    backgroundColor: "#fff",
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    overflow: "hidden",
  },
  notificationDot: {
    width: 8,
    height: 8,
    backgroundColor: "#ef4444",
    borderRadius: 4,
    position: "absolute",
    right: -2,
    top: -2,
  },
  bellEmoji: { fontSize: 16 },
  avatarRight: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#c084fc",
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 24,
    padding: 14,
    marginBottom: 12,
    elevation: 2,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
    gap: 8,
  },
  cardHeaderTitle: {
    fontSize: 16,
    fontWeight: "700",
  },
  grid2: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 10,
  },
  smallCard: {
    flex: 1,
    borderRadius: 16,
    padding: 12,
    marginRight: 8,
  },
  smallCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  iconBox: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  iconText: { fontSize: 18, color: "#fff" },
  deltaText: { fontSize: 12, color: "#16a34a", fontWeight: "600" },
  bigNumber: { fontSize: 28, fontWeight: "800", marginTop: 6 },
  smallMuted: { fontSize: 13, color: "#6b7280" },
  smallMutedExtra: { fontSize: 11, color: "#9ca3af" },
  calendarHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  calendarTitle: { fontSize: 16, fontWeight: "700", color: "#db2777" },
  monthBtns: { flexDirection: "row" },
  monthButton: {
    width: 36,
    height: 36,
    backgroundColor: "#fff0f6",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    marginLeft: 8,
  },
  monthButtonText: { fontSize: 18 },
  weekRow: {
    marginTop: 12,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  weekDayCell: { alignItems: "center" },
  weekDayText: { fontSize: 12, color: "#6b7280" },
  calendarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: 8,
  },
  calendarCell: {
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    marginBottom: 8,
  },
  calendarCellEmpty: { opacity: 0 },
  calendarCellSelected: {
    backgroundColor: "#fb923c",
    shadowColor: "#fb923c",
    shadowRadius: 6,
    elevation: 3,
  },
  calendarCellText: { fontSize: 13, color: "#374151" },
  calendarCellTextSelected: { color: "#fff", fontWeight: "700" },
  calendarCellToday: { borderWidth: 2, borderColor: "#fb923c" },
  calendarCellTextToday: { color: "#fb923c", fontWeight: "700" },
  eventDot: {
    position: "absolute",
    bottom: 4,
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#fb923c",
  },
  eventCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fafafa",
    padding: 12,
    borderRadius: 12,
    marginBottom: 8,
    borderLeftWidth: 3,
    borderLeftColor: "#fb923c",
  },
  eventCardCompleted: { opacity: 0.7, borderLeftColor: "#10b981" },
  eventIcon: { fontSize: 24, marginRight: 12 },
  eventTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#111827",
    marginBottom: 4,
  },
  eventTitleCompleted: { textDecorationLine: "line-through", color: "#6b7280" },
  eventType: { fontSize: 12, color: "#6b7280", textTransform: "capitalize" },
  statusBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12 },
  statusPending: { backgroundColor: "#fff7ed" },
  statusCompleted: { backgroundColor: "#d1fae5" },
  statusText: { fontSize: 11, fontWeight: "700", color: "#f97316" },
  statusTextCompleted: { color: "#10b981" },
  subjectHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  subjectIconBox: {
    width: 34,
    height: 34,
    borderRadius: 8,
    backgroundColor: "#fff0f6",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
  },
  subjectTitle: { fontSize: 16, fontWeight: "700" },
  toggleTrack: {
    width: 48,
    height: 26,
    borderRadius: 20,
    padding: 3,
    justifyContent: "center",
  },
  toggleOn: { backgroundColor: "#fb7185" },
  toggleOff: { backgroundColor: "#e5e7eb" },
  toggleKnob: {
    width: 20,
    height: 20,
    borderRadius: 12,
    backgroundColor: "#fff",
    elevation: 2,
  },
  toggleKnobOn: { alignSelf: "flex-end" },
  toggleKnobOff: { alignSelf: "flex-start" },
  subjectRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  subjectName: { fontSize: 14, fontWeight: "600", color: "#374151" },
  subjectStat: { fontSize: 13, fontWeight: "700" },
  progressBg: {
    height: 10,
    backgroundColor: "#f3f4f6",
    borderRadius: 8,
    overflow: "hidden",
    marginTop: 8,
  },
  progressFill: { height: 10, borderRadius: 8 },
  absencesText: { fontSize: 12, color: "#6b7280", marginTop: 6 },
  activityRow: {
    flexDirection: "row",
    alignItems: "center",
    padding: 10,
    borderRadius: 12,
    marginBottom: 8,
  },
  statusCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  activityName: { fontSize: 13, fontWeight: "700", color: "#111827" },
  activityStatus: { fontSize: 12, fontWeight: "700" },
});
