import { StyleSheet } from "react-native";

export default StyleSheet.create({
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 10,
    paddingBottom: 8,
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "transparent",
  },
  menuButton: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
  },
  logo: {
    width: 42,
    height: 42,
    borderRadius: 21,
  },
  profileTrigger: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 6,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  profileName: {
    maxWidth: 120,
    fontSize: 13,
    color: "#334155",
    fontWeight: "600",
  },
  avatarContainer: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#8B5CF6",
  },
  avatarText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "700",
  },

  dropdownModalRoot: {
    flex: 1,
  },
  dropdownBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(15, 23, 42, 0.2)",
  },
  dropdownContainer: {
    position: "absolute",
    top: 62,
    right: 16,
    minWidth: 196,
  },
  dropdownCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.16,
    shadowRadius: 20,
    elevation: 10,
    overflow: "hidden",
  },
  dropdownHeader: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
    backgroundColor: "#F8FAFC",
  },
  dropdownName: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1F2937",
  },
  dropdownRole: {
    marginTop: 2,
    fontSize: 11,
    color: "#6B7280",
    fontWeight: "500",
  },
  dropdownItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  dropdownItemText: {
    fontSize: 14,
    color: "#374151",
    fontWeight: "600",
  },
  dropdownItemTextDanger: {
    fontSize: 14,
    color: "#E11D48",
    fontWeight: "600",
  },

  drawerModalRoot: {
    flex: 1,
  },
  drawerBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(15, 23, 42, 0.45)",
  },
  drawerBackdropPressable: {
    flex: 1,
  },
  drawerPanel: {
    position: "absolute",
    top: 0,
    left: 0,
    bottom: 0,
    width: "82%",
    maxWidth: 320,
    backgroundColor: "#FFFFFF",
    borderTopRightRadius: 16,
    borderBottomRightRadius: 16,
    shadowColor: "#0F172A",
    shadowOffset: { width: 4, height: 0 },
    shadowOpacity: 0.22,
    shadowRadius: 16,
    elevation: 14,
  },
  drawerHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: 56,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
    backgroundColor: "#F8FAFC",
  },
  drawerBrandBlock: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    marginRight: 10,
  },
  drawerBrandLogo: {
    width: 50,
    height: 50,
    borderRadius: 999,
    marginRight: 10,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  drawerBrandTextWrap: {
    flex: 1,
    justifyContent: "center",
    paddingRight: 4,
  },
  drawerBrandTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#1F2937",
    lineHeight: 18,
    letterSpacing: 0.2,
  },
  drawerBrandTitleAccent: {
    color: "#6366F1",
    fontWeight: "800",
  },
  drawerBrandSubtitle: {
    marginTop: 3,
    fontSize: 10,
    lineHeight: 13,
    color: "#64748B",
    fontWeight: "500",
  },
  drawerTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1F2937",
  },
  drawerCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  drawerScroll: {
    flex: 1,
  },
  drawerScrollContent: {
    paddingVertical: 12,
    paddingHorizontal: 10,
  },
  drawerItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 11,
    paddingHorizontal: 10,
    borderRadius: 10,
    marginBottom: 6,
  },
  drawerItemActive: {
    backgroundColor: "#F8FAFC",
  },
  drawerItemIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  drawerItemText: {
    fontSize: 14,
    color: "#334155",
    fontWeight: "600",
  },

  confirmModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
  },
  confirmModalContainer: {
    width: "100%",
    maxWidth: 340,
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    paddingVertical: 28,
    paddingHorizontal: 24,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 20,
  },
  confirmIconContainer: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: "#FEF2F2",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
  },
  confirmTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: "#1F2937",
    marginBottom: 8,
  },
  confirmMessage: {
    fontSize: 15,
    color: "#6B7280",
    textAlign: "center",
    lineHeight: 22,
    marginBottom: 24,
  },
  confirmButtonRow: {
    flexDirection: "row",
    width: "100%",
    gap: 12,
  },
  confirmCancelButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: "#F3F4F6",
    alignItems: "center",
    justifyContent: "center",
  },
  confirmCancelText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#6B7280",
  },
  confirmLogoutButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: "#DC2626",
    alignItems: "center",
    justifyContent: "center",
  },
  confirmLogoutText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#FFFFFF",
  },
});
