import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFE4F0",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  headerRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  notificationBadge: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  notificationText: {
    fontSize: 18,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#9C27B0",
  },
  scrollView: {
    flex: 1,
    paddingHorizontal: 16,
  },
  subjectCard: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 16,
    marginBottom: 16,
  },
  subjectIconContainer: {
    flexDirection: "row",
    marginBottom: 16,
  },
  subjectIcon: {
    width: 56,
    height: 56,
    borderRadius: 16,
    backgroundColor: "#E91E63",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  subjectIconText: {
    fontSize: 28,
  },
  subjectInfo: {
    flex: 1,
  },
  subjectHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 4,
  },
  subjectTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#1A1A1A",
    flex: 1,
  },
  finalGradeBadge: {
    alignItems: "flex-end",
  },
  finalGradeLabel: {
    fontSize: 10,
    color: "#999",
    marginBottom: 2,
  },
  finalGradeValue: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#00C853",
  },
  finalGradeTotal: {
    fontSize: 12,
    color: "#999",
  },
  teacherText: {
    fontSize: 12,
    color: "#666",
  },
  exportButton: {
    flexDirection: "row",
    backgroundColor: "#E91E63",
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  exportButtonText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
  },
  quarterTabs: {
    marginBottom: 16,
  },
  quarterTab: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    gap: 8,
  },
  quarterTabActive: {},
  quarterDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#E91E63",
  },
  quarterDotInactive: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#E91E63",
    opacity: 0.3,
  },
  quarterTabText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#1A1A1A",
  },
  section: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 16,
    marginBottom: 12,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#1A1A1A",
  },
  sectionContent: {
    marginTop: 16,
  },
  workItem: {
    marginBottom: 16,
  },
  workHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  workTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#1A1A1A",
  },
  workScore: {
    fontSize: 14,
    fontWeight: "700",
    color: "#00C853",
  },
  workDescription: {
    fontSize: 13,
    color: "#666",
    marginBottom: 8,
  },
  statusBadge: {
    alignSelf: "flex-start",
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
  },
  statusText: {
    fontSize: 11,
    fontWeight: "600",
    color: "#fff",
  },
  examCard: {
    alignItems: "center",
    paddingVertical: 16,
  },
  examScore: {
    fontSize: 32,
    fontWeight: "bold",
    color: "#00C853",
    marginBottom: 8,
  },
  quarterPlaceholder: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 24,
    marginBottom: 12,
    alignItems: "center",
  },
  quarterHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
    gap: 8,
  },
  quarterHeaderText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#1A1A1A",
  },
  placeholderIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#FFE4F0",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  placeholderEmoji: {
    fontSize: 36,
  },
  placeholderText: {
    fontSize: 13,
    color: "#666",
    textAlign: "center",
    lineHeight: 20,
  },
  feedbackSection: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 16,
    marginBottom: 12,
  },
  feedbackHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
    gap: 8,
  },
  feedbackIconBox: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: "#FFE4F0",
    alignItems: "center",
    justifyContent: "center",
  },
  feedbackIcon: {
    fontSize: 16,
  },
  feedbackTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#E91E63",
  },
  feedbackItem: {
    marginBottom: 12,
  },
  feedbackQuarter: {
    fontSize: 13,
    fontWeight: "700",
    color: "#E91E63",
    marginBottom: 4,
  },
  feedbackText: {
    fontSize: 13,
    color: "#666",
    lineHeight: 18,
  },
  interventionSection: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 16,
    marginBottom: 12,
  },
  interventionHeader: {
    marginBottom: 16,
  },
  interventionTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#E91E63",
  },
  interventionPlaceholder: {
    alignItems: "center",
    paddingVertical: 16,
  },
  interventionIconBox: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "#D1FAE5",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  interventionIcon: {
    fontSize: 28,
  },
  interventionText: {
    fontSize: 13,
    color: "#666",
    textAlign: "center",
  },
  trendSection: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 20,
    marginBottom: 16,
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
  },
  trendHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 6,
  },
  trendIcon: { fontSize: 22 },
  trendTitle: { fontSize: 17, fontWeight: "bold", color: "#E91E63" },
  trendSubtitle: {
    fontSize: 12,
    color: "#6B7280",
    textAlign: "center",
    marginBottom: 16,
  },
  summaryRow: { flexDirection: "row", gap: 10, marginBottom: 20 },
  summaryCard: {
    flex: 1,
    backgroundColor: "#F9FAFB",
    padding: 12,
    borderRadius: 14,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  summaryLabel: {
    fontSize: 10,
    color: "#6B7280",
    fontWeight: "600",
    marginBottom: 4,
  },
  summaryValue: { fontSize: 19, fontWeight: "bold", color: "#111827" },
  avgTag: {
    fontSize: 9,
    backgroundColor: "#10B981",
    color: "white",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
    marginLeft: 6,
    fontWeight: "bold",
  },
  trendDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#10B981",
  },
  trendText: { color: "#10B981", fontWeight: "bold", fontSize: 14 },
  trendDirection: { flexDirection: "row", alignItems: "center", gap: 6 },
  chartContainer: {
    alignItems: "left",
    justifyContent: "center",
    backgroundColor: "#FCFCFD",
    borderRadius: 16,
    paddingVertical: 0,
    marginVertical: 10,
    borderWidth: 1,
    borderColor: "#F1F5F9",
  },
  pointerLabel: {
    backgroundColor: "#1E1B4B",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    marginTop: 90,
    alignItems: "center",
  },
  pointerQuarter: { color: "#C4B5FD", fontSize: 12, fontWeight: "bold" },
  pointerValue: { color: "#FFFFFF", fontSize: 22, fontWeight: "bold" },
  quarterBreakdown: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginTop: 16,
  },
  quarterItem: { alignItems: "center" },
  quarterLabel: { color: "#64748B", fontSize: 12, marginBottom: 4 },
  quarterGrade: { fontSize: 23, fontWeight: "bold", color: "#111827" },
  changeText: {
    color: "#10B981",
    fontSize: 11,
    fontWeight: "600",
    marginTop: 2,
  },
  changeTextDecline: {
    color: "#EF4444",
    fontSize: 11,
    fontWeight: "600",
    marginTop: 2,
  },
  changeTextBest: {
    color: "#10B981",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 2,
  },
  summaryNote: {
    backgroundColor: "#F0FDF4",
    padding: 16,
    borderRadius: 14,
    marginTop: 16,
    borderWidth: 1,
    borderColor: "#BBF7D0",
  },
  summaryNoteText: {
    color: "#166534",
    fontSize: 13.5,
    lineHeight: 20,
    textAlign: "center",
    fontWeight: "500",
  },
});
